### ISSUE TITLE
C99 mode error

### ISSUE THREAD

**Issue by bqwzhl20** [kakwa/uts-server#1]
/root/uts-server-master/src/lib/rfc3161.c: In function ‘get_ctxw’:
/root/uts-server-master/src/lib/rfc3161.c:73: error: ‘for’ loop initial declarations are only allowed in C99 mode
/root/uts-server-master/src/lib/rfc3161.c:73: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: **\* [CMakeFiles/uts-server.dir/src/lib/rfc3161.c.o] Error 1
make[1]: **\* [CMakeFiles/uts-server.dir/all] Error 2
make: **\* [all] Error 2

**Comment by kakwa** [comment]
Thank you for reporting this bug

Commit: https://github.com/kakwa/uts-server/commit/b98d15b5d61d89d508f50f0889995556ee349591 should fix the issue.

Could you confirm it?

**Comment by bqwzhl20** [comment]
yes, it's ok now, thx.
