### ISSUE TITLE
Source for Time Stamp Certificate

### ISSUE THREAD

**Issue by mavajikitl** [kakwa/uts-server#19]
Hi

Script given for certificate generation in this project is created test certificates for time stamping( Which has no Trusted CA - Certificate Authority)

Can anyone provide the link or provider detail who can provide the Time stamping certificate with Trusted CA ?

**Comment by kakwa** [comment]
Well, that's up to you.

uts-server is a piece of software. Not a service like http://timestamp.digicert.com/.

If you deploy it, you need to create your own certificate+key, signed by a valid CA (either your own internal one, or an external one).
Just be sure to generate a CSR with the appropriate parameters: https://uts-server.readthedocs.io/en/latest/configure.html#section-tsa
