### ISSUE TITLE
zlib

### ISSUE THREAD

**Issue by abrca** [kakwa/uts-server#3]
zlib is required to compile civetweb, so it's better to add check

find_package(ZLIB REQUIRED)
MESSAGE(STATUS "ZLIB libraries: ${ZLIB_LIBRARIES}")
MESSAGE(STATUS "ZLIB version: ${ZLIB_VERSION_STRING}")

in CMakeLists.txt (near find_package(OPENSSL REQUIRED))

**Comment by kakwa** [comment]
It seems more related to civetweb than uts-server. It looks more logical to open a bug there https://github.com/civetweb/civetweb.

By the way, I don't see any include of zlib in civetweb, and civetweb doesn't support on the fly compression according to https://github.com/civetweb/civetweb/issues/199, I'm not sure that's a real issue.

**Comment by abrca** [comment]
Yes, probably these is openssl dependency
