### ISSUE TITLE
FreeBSD CLang problem

### ISSUE THREAD

**Issue by abrca** [kakwa/uts-server#5]
Compiling statically linked executable (as described in issue #4 ), ends with error:

[100%] Linking C executable uts-server
/usr/bin/ld: undefined reference to symbol `__register_frame_info@@GCC_3.0' (try adding -lgcc_s)
//lib/libgcc_s.so.1: could not read symbols: Bad value
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

FreeBSD 11.0, CLang 3.8.0. Using gcc 4.9.4 - compiles ok.

**Comment by kakwa** [comment]
using the new ```-DLINK_GCC_S=ON``` (switch enable linking against gcc_s) the problem is fixed.

**Comment by abrca** [comment]
in CMakeLists.txt duplicate options LINKDL:

option(LINKDL "dynamicaly link dl" OFF)
option(LINKDL "dynamicaly link gcc_s" OFF)

second must be LINK_GCC_S ?

**Comment by kakwa** [comment]
yes, fixing it
