### ISSUE TITLE
duplication parameters

### ISSUE THREAD

**Issue by abrca** [kakwa/uts-server#6]
in CMakeLists.txt
-DCIVETWEB_DISABLE_CGI=ON
is set twice, in 75 and 78 lines

and, just curiosity question: what's the sense of patching civetweb sources - replacing __DATE__ with "110973"?

**Comment by kakwa** [comment]
__DATE__ may and have triggered warnings because it induces a non reproducible build (which depending on compile flags, may result in failures). The 110973 is a (not so) random date.

Will fix the duplicate option.
